apiVersion: v1
kind: ServiceAccount
metadata:
  name: nexus
automountServiceAccountToken: false
---
apiVersion: v1
kind: Namespace
metadata:
  name: nexus
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: nexus
subjects:
  - kind: ServiceAccount
    name: nexus
    namespace: nexus
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
