apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-proxy-deployment
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus-proxy
    spec:
      serviceAccountName: monitoring
      containers:
        - name: prometheus-proxy
          image: micrometermetrics/prometheus-rsocket-proxy:latest
          ports:
            - name: scrape
              containerPort: 8080
            - name: rsocket
              containerPort: 7001
      securityContext:
        fsGroup: 2000
        runAsNonRoot: true
        runAsUser: 1000
