{
 "title": "HTTP Request Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Request throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=\"/persons\"}[1m])) by (foundation)",
     "legendFormat": "{{foundation}}"
    }
   ]
  },
  {
   "title": "Throughput by instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_max{uri=\"/persons\", status=\"200\"}) by (app, foundation, cf_instance_number)",
     "legendFormat": "{{foundation}} {{app}} {{cf_instance_number}}"
    }
   ]
  },
  {
   "title": "Failure rate by foundation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=\"/persons\", status!=\"200\"}[1m])) by (foundation)",
     "legendFormat": "{{foundation}}"
    }
   ]
  },
  {
   "title": "Failures by instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{uri=\"/persons\", status!=\"200\"}[1m])",
     "legendFormat": "{{foundation}} {{app}} {{cf_instance_number}}"
    }
   ]
  },
  {
   "title": "Successful responses to /persons",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_bucket{uri=\"/persons\", status=\"200\", le=~\"0\\\\.[0-4]\\\\d+|\\\\+Inf\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Max latency by instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_max{uri=\"/persons\", status=\"200\"}) by (app, foundation, cf_instance_number)",
     "legendFormat": "{{foundation}} {{app}} {{cf_instance_number}}"
    }
   ]
  }
 ]
}