apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
 #   cloud.google.com/load-balancer-type: "Internal"
  name: grafana
  namespace: monitoring
  labels:
    name: grafana
spec:
  selector:
    app: grafana
  ports:
    - name: grafana
      port: 80
      targetPort: 3000
  type: LoadBalancer
